namespace: nagios
name: nagios
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/nagios.nagios.git
documentation: https://github.com/coll-test/nagios.nagios/tree/master/docs
homepage: https://github.com/coll-test/nagios.nagios
issues: https://github.com/coll-test/nagios.nagios/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
